### ISSUE TITLE
How to add more options?

### ISSUE THREAD

**Issue by Technologx** [valdio/AudioPlayer#1]
How can I add shuffle, repeat, random & a actual screen that shows the progress? Also the notification options keep showing back up after I swipe them away.

**Comment by valdio** [comment]
The solution is only for playing one audio at a time ...... to create shuffle I recommend creating function to play a random media file and call it in the OnCompletionListener method.... the same goes for repeat..... just set some flag to notify which are you interested in playing, shuffle or repeat


Getting the progress back I recommend creating a broadcast receiver to broadcast the player progress on the activity.

**Comment by Technologx** [comment]
Would you be willing to help me with this I found your tutorial to make this app? I'm a noob to Android coding and could use some help if you don't mind. I don't have money to pay you for your work or I would. Here's a link to my project: https://github.com/Technologx/Blaze-Player/blob/master/README.md

**Comment by valdio** [comment]
Sorry, I don't have the time right now and my Audio player app requires a few changes to add the features you require.

**Comment by Technologx** [comment]
Are they big changes?
