### ISSUE TITLE
New Logo / Icon

### ISSUE THREAD

**Issue by luthfirangers** [valdio/AudioPlayer#6]
Hi @valdio , I am a graphic designer, I want to help others in graphic design.

After I review your project, your logo is just a crop photo on this project. Therefore I would like to contribute to this project by creating a more interesting new logo / icon.

**Comment by valdio** [comment]
Thanks, @luthfirangers  for offering to make a logo, but this is sample app, not a full featured project and as such it does not need a logo.

Thank you anyway. I appreciate it.
