### ISSUE TITLE
Service stops in background.  

### ISSUE THREAD

**Issue by carloscj6** [valdio/AudioPlayer#8]
The service is running well, but as not expected, when I clear apps through overview  button, the service wtops. Pls give a fix. Music apps keep running even when recent apps are cleared.

**Comment by valdio** [comment]
@carloscj6 The service is destroyed on the onDesptroy method of the MainAnctivity.

https://github.com/valdio/AudioPlayer/blob/902ee29fdfcfe0aeee80c3138396a9add8fa6f62/app/src/main/java/com/valdioveliu/valdio/audioplayer/MainActivity.java#L318

If you remove the code from onDestroy the service will keep playing

**Comment by carloscj6** [comment]
Still didn't work. It stops then restarts the service. I need to have it running after ondestroy without any interference.  Thanks
